### ISSUE TITLE
Could you provide the code for Stable Diffusion?

### ISSUE THREAD

**Issue by njuaplusplus** [kong13661/PIA#1]
Thanks for your work.
I wonder if you could provide the code for Stable Diffusion.

**Comment by kong13661** [comment]
We have push the stable diffusion code. If you have any problem, please let up know.

**Comment by njuaplusplus** [comment]
Thank you very much.
Could you provide some examples for the `norm_p` parameter?

**Comment by njuaplusplus** [comment]
There are many bugs in the code. Could you fix them?

**Comment by njuaplusplus** [comment]
For example, 

`attacker` returns a single distance, but [Line 172](https://github.com/kong13661/PIA/blob/main/stable_diffusion/stable_attack.py#L172) requires `intermediate_reverse_member, intermediate_denoise_member`.

[Line 181](https://github.com/kong13661/PIA/blob/main/stable_diffusion/stable_attack.py#L181) makes `member` a list. But [Line 184](https://github.com/kong13661/PIA/blob/main/stable_diffusion/stable_attack.py#L184) calls `shape` which it doesn't have.
